//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppUscv.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class catAsociaciones
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public catAsociaciones()
        {
            this.tblPersonalAsociaciones = new HashSet<tblPersonalAsociaciones>();
        }
    
        public int id { get; set; }
        public string descripcion { get; set; }
        public Nullable<int> fkTipoEmpresa { get; set; }
    
        public virtual CatTipoEmpresa CatTipoEmpresa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPersonalAsociaciones> tblPersonalAsociaciones { get; set; }
    }
}
