//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppUscv.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class catComprobanteDomicilio
    {
        public int id { get; set; }
        public Nullable<int> fkPersonal { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public byte[] comprobante { get; set; }
    
        public virtual tblPersonal tblPersonal { get; set; }
    }
}
