//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppUscv.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class catDocumentos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public catDocumentos()
        {
            this.detalletblProyecto_catDocumentos = new HashSet<detalletblProyecto_catDocumentos>();
            this.tblCursos = new HashSet<tblCursos>();
            this.tblDesempeñoLaboralAdministrativoDentro = new HashSet<tblDesempeñoLaboralAdministrativoDentro>();
            this.tblDocumentacionPersonal = new HashSet<tblDocumentacionPersonal>();
            this.tblDocumentacionRHFueraUT = new HashSet<tblDocumentacionRHFueraUT>();
            this.tblNivelEstudio = new HashSet<tblNivelEstudio>();
            this.tblNivelEstudio1 = new HashSet<tblNivelEstudio>();
            this.tblNivelEstudio2 = new HashSet<tblNivelEstudio>();
            this.tblNivelEstudioAdministrativo = new HashSet<tblNivelEstudioAdministrativo>();
            this.tblNivelEstudioAdministrativo1 = new HashSet<tblNivelEstudioAdministrativo>();
            this.tblNivelEstudioAdministrativo2 = new HashSet<tblNivelEstudioAdministrativo>();
            this.tblPremiosDocente = new HashSet<tblPremiosDocente>();
            this.tblEstadia = new HashSet<tblEstadia>();
            this.tblProduccionAcademica = new HashSet<tblProduccionAcademica>();
            this.tblSuperacionProfecional = new HashSet<tblSuperacionProfecional>();
            this.tblDatosLaboralesDocente = new HashSet<tblDatosLaboralesDocente>();
            this.tblParticipacionDocente = new HashSet<tblParticipacionDocente>();
        }
    
        public int id { get; set; }
        public string documento { get; set; }
        public byte[] archivo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalletblProyecto_catDocumentos> detalletblProyecto_catDocumentos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCursos> tblCursos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblDesempeñoLaboralAdministrativoDentro> tblDesempeñoLaboralAdministrativoDentro { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblDocumentacionPersonal> tblDocumentacionPersonal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblDocumentacionRHFueraUT> tblDocumentacionRHFueraUT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblNivelEstudio> tblNivelEstudio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblNivelEstudio> tblNivelEstudio1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblNivelEstudio> tblNivelEstudio2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblNivelEstudioAdministrativo> tblNivelEstudioAdministrativo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblNivelEstudioAdministrativo> tblNivelEstudioAdministrativo1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblNivelEstudioAdministrativo> tblNivelEstudioAdministrativo2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPremiosDocente> tblPremiosDocente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblEstadia> tblEstadia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblProduccionAcademica> tblProduccionAcademica { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSuperacionProfecional> tblSuperacionProfecional { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblDatosLaboralesDocente> tblDatosLaboralesDocente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblParticipacionDocente> tblParticipacionDocente { get; set; }
    }
}
