//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppUscv.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class catDisciplinas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public catDisciplinas()
        {
            this.tblNivelEstudio = new HashSet<tblNivelEstudio>();
            this.tblProyectosInvestigacionPromep = new HashSet<tblProyectosInvestigacionPromep>();
        }
    
        public int idDisciplina { get; set; }
        public string disciplina { get; set; }
        public Nullable<int> fkArea { get; set; }
    
        public virtual catAreasEstudio catAreasEstudio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblNivelEstudio> tblNivelEstudio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblProyectosInvestigacionPromep> tblProyectosInvestigacionPromep { get; set; }
    }
}
