//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppUscv.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class catFamiliar
    {
        public int id { get; set; }
        public Nullable<int> fkParentesco { get; set; }
        public string nombre { get; set; }
        public Nullable<bool> vive { get; set; }
        public string domicilio { get; set; }
        public string ocupacion { get; set; }
        public Nullable<int> edad { get; set; }
        public Nullable<int> fkPersonal { get; set; }
        public Nullable<System.DateTime> cumpleañosHijos { get; set; }
    
        public virtual catParentesco catParentesco { get; set; }
        public virtual tblPersonal tblPersonal { get; set; }
    }
}
