//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppUscv.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class CatLineasInvestigacion
    {
        public int id { get; set; }
        public string descripcion { get; set; }
        public Nullable<int> fkCuerpoAcademico { get; set; }
    
        public virtual CatCuerpoAcademico CatCuerpoAcademico { get; set; }
    }
}
