//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppUscv.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class catMaterias
    {
        public int id { get; set; }
        public string materia { get; set; }
        public Nullable<int> fkProgramaEducativo { get; set; }
        public Nullable<int> fkCuatrimestre { get; set; }
        public Nullable<int> fkUnidad { get; set; }
    
        public virtual catCuatrimestre catCuatrimestre { get; set; }
        public virtual catProgramaEducativo catProgramaEducativo { get; set; }
        public virtual catUnidades catUnidades { get; set; }
    }
}
