//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppUscv.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class catProgramaEducativo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public catProgramaEducativo()
        {
            this.catMaterias = new HashSet<catMaterias>();
            this.tblDatosLaboralesDocente = new HashSet<tblDatosLaboralesDocente>();
            this.tblDocumentacionRHDentroUT = new HashSet<tblDocumentacionRHDentroUT>();
            this.tblEstadia = new HashSet<tblEstadia>();
            this.tblProduccionAcademica = new HashSet<tblProduccionAcademica>();
            this.tblTutorias = new HashSet<tblTutorias>();
        }
    
        public int id { get; set; }
        public string carrera { get; set; }
        public Nullable<int> fkinstitucionsuperior { get; set; }
        public Nullable<int> fkTipoEstudio { get; set; }
    
        public virtual catInstitucionSuperior catInstitucionSuperior { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<catMaterias> catMaterias { get; set; }
        public virtual catTipoEstudio catTipoEstudio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblDatosLaboralesDocente> tblDatosLaboralesDocente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblDocumentacionRHDentroUT> tblDocumentacionRHDentroUT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblEstadia> tblEstadia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblProduccionAcademica> tblProduccionAcademica { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTutorias> tblTutorias { get; set; }
    }
}
