//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppUscv.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class catSalarios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public catSalarios()
        {
            this.catTipoContrato = new HashSet<catTipoContrato>();
        }
    
        public int id { get; set; }
        public Nullable<decimal> salario { get; set; }
        public Nullable<int> fkCatNivelSalarial { get; set; }
    
        public virtual CatNivelSalarial CatNivelSalarial { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<catTipoContrato> catTipoContrato { get; set; }
    }
}
