//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppUscv.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class catTipoContrato
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public catTipoContrato()
        {
            this.tblDatosLaboralesDocente = new HashSet<tblDatosLaboralesDocente>();
            this.tblDesempeñoLaboralAdministrativoDentro = new HashSet<tblDesempeñoLaboralAdministrativoDentro>();
            this.tblDocumentacionRHDentroUT = new HashSet<tblDocumentacionRHDentroUT>();
        }
    
        public int id { get; set; }
        public string descripcion { get; set; }
        public Nullable<int> fkCatCategoria { get; set; }
        public Nullable<int> fkCatSalario { get; set; }
    
        public virtual catCategoria catCategoria { get; set; }
        public virtual catSalarios catSalarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblDatosLaboralesDocente> tblDatosLaboralesDocente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblDesempeñoLaboralAdministrativoDentro> tblDesempeñoLaboralAdministrativoDentro { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblDocumentacionRHDentroUT> tblDocumentacionRHDentroUT { get; set; }
    }
}
