//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppUscv.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class detalletblProyecto_catDocumentos
    {
        public int fktblproyecto { get; set; }
        public int fkcatDocumento { get; set; }
        public string TipoDocumento { get; set; }
    
        public virtual catDocumentos catDocumentos { get; set; }
        public virtual tblProyecto tblProyecto { get; set; }
    }
}
