//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppUscv.Repository
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class bdGestionDocentesEntities : DbContext
    {
        public bdGestionDocentesEntities()
            : base("name=bdGestionDocentesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CatAcademias> CatAcademias { get; set; }
        public virtual DbSet<catAlergias> catAlergias { get; set; }
        public virtual DbSet<catArchivosRubricas> catArchivosRubricas { get; set; }
        public virtual DbSet<catArea> catArea { get; set; }
        public virtual DbSet<catAreasEstudio> catAreasEstudio { get; set; }
        public virtual DbSet<catAsociaciones> catAsociaciones { get; set; }
        public virtual DbSet<catCategoria> catCategoria { get; set; }
        public virtual DbSet<catCompetencias> catCompetencias { get; set; }
        public virtual DbSet<catCompetenciasTIEspecificas> catCompetenciasTIEspecificas { get; set; }
        public virtual DbSet<catCompetenciaTI> catCompetenciaTI { get; set; }
        public virtual DbSet<catComprobanteDomicilio> catComprobanteDomicilio { get; set; }
        public virtual DbSet<catCuatrimestre> catCuatrimestre { get; set; }
        public virtual DbSet<CatCuerpoAcademico> CatCuerpoAcademico { get; set; }
        public virtual DbSet<catCurso> catCurso { get; set; }
        public virtual DbSet<catDeportes> catDeportes { get; set; }
        public virtual DbSet<catDisciplinas> catDisciplinas { get; set; }
        public virtual DbSet<catDocumentos> catDocumentos { get; set; }
        public virtual DbSet<catEdificio> catEdificio { get; set; }
        public virtual DbSet<catEdoCivil> catEdoCivil { get; set; }
        public virtual DbSet<catEnfermedad> catEnfermedad { get; set; }
        public virtual DbSet<catEstado> catEstado { get; set; }
        public virtual DbSet<catFamiliar> catFamiliar { get; set; }
        public virtual DbSet<catFrecuencia> catFrecuencia { get; set; }
        public virtual DbSet<CatFunciones> CatFunciones { get; set; }
        public virtual DbSet<catIdiomasDialecto> catIdiomasDialecto { get; set; }
        public virtual DbSet<catInstitucionPremiosDistincio> catInstitucionPremiosDistincio { get; set; }
        public virtual DbSet<catInstitucionSuperior> catInstitucionSuperior { get; set; }
        public virtual DbSet<CatLineasInvestigacion> CatLineasInvestigacion { get; set; }
        public virtual DbSet<catLocalidad> catLocalidad { get; set; }
        public virtual DbSet<catMaterias> catMaterias { get; set; }
        public virtual DbSet<catMunicipio> catMunicipio { get; set; }
        public virtual DbSet<CatNivelSalarial> CatNivelSalarial { get; set; }
        public virtual DbSet<catPais> catPais { get; set; }
        public virtual DbSet<catParentesco> catParentesco { get; set; }
        public virtual DbSet<catPeriodo> catPeriodo { get; set; }
        public virtual DbSet<CatProduccion> CatProduccion { get; set; }
        public virtual DbSet<catProduccionArtistica> catProduccionArtistica { get; set; }
        public virtual DbSet<catProgramaEducativo> catProgramaEducativo { get; set; }
        public virtual DbSet<catSalarios> catSalarios { get; set; }
        public virtual DbSet<CatStatusEstudio> CatStatusEstudio { get; set; }
        public virtual DbSet<catTipoActividad> catTipoActividad { get; set; }
        public virtual DbSet<catTipoAlergias> catTipoAlergias { get; set; }
        public virtual DbSet<catTipoContrato> catTipoContrato { get; set; }
        public virtual DbSet<CatTipoEmpresa> CatTipoEmpresa { get; set; }
        public virtual DbSet<catTipoEstudio> catTipoEstudio { get; set; }
        public virtual DbSet<catTipoSangre> catTipoSangre { get; set; }
        public virtual DbSet<catUnidades> catUnidades { get; set; }
        public virtual DbSet<catUnidadesAcademicas> catUnidadesAcademicas { get; set; }
        public virtual DbSet<detalletblProyecto_catDocumentos> detalletblProyecto_catDocumentos { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tblConocimientoGeneral> tblConocimientoGeneral { get; set; }
        public virtual DbSet<tblCursos> tblCursos { get; set; }
        public virtual DbSet<tblDatosLaboralesAdministrativos> tblDatosLaboralesAdministrativos { get; set; }
        public virtual DbSet<tblDatosLaboralesDocente> tblDatosLaboralesDocente { get; set; }
        public virtual DbSet<tblDesempeñoLaboralAdministrativoDentro> tblDesempeñoLaboralAdministrativoDentro { get; set; }
        public virtual DbSet<tblDireccionIndividualizada> tblDireccionIndividualizada { get; set; }
        public virtual DbSet<tblDistincionesPersonal> tblDistincionesPersonal { get; set; }
        public virtual DbSet<tblDocumentacionPersonal> tblDocumentacionPersonal { get; set; }
        public virtual DbSet<tblDocumentacionRHDentroUT> tblDocumentacionRHDentroUT { get; set; }
        public virtual DbSet<tblDocumentacionRHFueraUT> tblDocumentacionRHFueraUT { get; set; }
        public virtual DbSet<tblEmergencia> tblEmergencia { get; set; }
        public virtual DbSet<tblEstadia> tblEstadia { get; set; }
        public virtual DbSet<tblEstudio> tblEstudio { get; set; }
        public virtual DbSet<tblLibros> tblLibros { get; set; }
        public virtual DbSet<tblNivelEstudio> tblNivelEstudio { get; set; }
        public virtual DbSet<tblNivelEstudioAdministrativo> tblNivelEstudioAdministrativo { get; set; }
        public virtual DbSet<tblParticipacionDocente> tblParticipacionDocente { get; set; }
        public virtual DbSet<tblPersonal> tblPersonal { get; set; }
        public virtual DbSet<tblPersonalAsociaciones> tblPersonalAsociaciones { get; set; }
        public virtual DbSet<tblPersonalDeporte> tblPersonalDeporte { get; set; }
        public virtual DbSet<tblPersonas> tblPersonas { get; set; }
        public virtual DbSet<tblPortafolioPersonal> tblPortafolioPersonal { get; set; }
        public virtual DbSet<tblPremiosDocente> tblPremiosDocente { get; set; }
        public virtual DbSet<tblProduccionAcademica> tblProduccionAcademica { get; set; }
        public virtual DbSet<tblProyecto> tblProyecto { get; set; }
        public virtual DbSet<tblProyectosInvestigacionPromep> tblProyectosInvestigacionPromep { get; set; }
        public virtual DbSet<tblSuperacionProfecional> tblSuperacionProfecional { get; set; }
        public virtual DbSet<tblTutorias> tblTutorias { get; set; }
        public virtual DbSet<tblDocumentosRH> tblDocumentosRH { get; set; }
    }
}
