//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppUscv.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblConocimientoGeneral
    {
        public int fkPersonal { get; set; }
        public int fkIdiomaDialecto { get; set; }
        public string comunicacionPorcentaje { get; set; }
        public string entendimientoPorcentaje { get; set; }
        public string escrituraPorcentaje { get; set; }
        public string lecturaPorcentaje { get; set; }
    }
}
