//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppUscv.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDesempeñoLaboralAdministrativoDentro
    {
        public int id { get; set; }
        public Nullable<int> fkCatArea { get; set; }
        public Nullable<int> fkCatPeriodo { get; set; }
        public Nullable<int> fkCatDocumentos { get; set; }
        public Nullable<int> fkPersonal { get; set; }
        public Nullable<int> fkTipoContrato { get; set; }
    
        public virtual catArea catArea { get; set; }
        public virtual catDocumentos catDocumentos { get; set; }
        public virtual catPeriodo catPeriodo { get; set; }
        public virtual catTipoContrato catTipoContrato { get; set; }
        public virtual tblPersonal tblPersonal { get; set; }
    }
}
