//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppUscv.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDocumentacionRHDentroUT
    {
        public int id { get; set; }
        public Nullable<int> fkPersonal { get; set; }
        public Nullable<int> fkCatTipoContrato { get; set; }
        public Nullable<int> fkArea { get; set; }
        public Nullable<System.DateTime> fechainiciocargo { get; set; }
        public Nullable<System.DateTime> fechaterminocargo { get; set; }
        public string institucion { get; set; }
        public Nullable<int> fkCatCategoria { get; set; }
        public string actividad { get; set; }
        public Nullable<int> fkProgramaEducativo { get; set; }
    
        public virtual catArea catArea { get; set; }
        public virtual catCategoria catCategoria { get; set; }
        public virtual catProgramaEducativo catProgramaEducativo { get; set; }
        public virtual catTipoContrato catTipoContrato { get; set; }
        public virtual tblPersonal tblPersonal { get; set; }
    }
}
