//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppUscv.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDatosLaboralesAdministrativos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblDatosLaboralesAdministrativos()
        {
            this.tblNivelEstudioAdministrativo = new HashSet<tblNivelEstudioAdministrativo>();
        }
    
        public int id { get; set; }
        public Nullable<int> fkCatArea { get; set; }
        public Nullable<int> fkTipoContrato { get; set; }
        public Nullable<int> fkPersonal { get; set; }
        public Nullable<System.DateTime> fechaNombramientoConsejo { get; set; }
        public Nullable<System.DateTime> fechaInicioUt { get; set; }
        public Nullable<int> fkCatUnidadesAcademicas { get; set; }
    
        public virtual catArea catArea { get; set; }
        public virtual catUnidadesAcademicas catUnidadesAcademicas { get; set; }
        public virtual tblPersonal tblPersonal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblNivelEstudioAdministrativo> tblNivelEstudioAdministrativo { get; set; }
    }
}
