//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppUscv.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDatosLaboralesDocente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblDatosLaboralesDocente()
        {
            this.tblNivelEstudio = new HashSet<tblNivelEstudio>();
            this.tblProduccionAcademica = new HashSet<tblProduccionAcademica>();
            this.catDocumentos = new HashSet<catDocumentos>();
        }
    
        public int id { get; set; }
        public Nullable<System.DateTime> fechaInicio { get; set; }
        public Nullable<int> fkProgramaEducativo { get; set; }
        public Nullable<int> fkTipoContrato { get; set; }
        public Nullable<int> fkPersonal { get; set; }
        public string emailInstitucional { get; set; }
        public string objetivoPersonal { get; set; }
        public string noExtencion { get; set; }
        public Nullable<int> fkCuerpoAcademico { get; set; }
        public Nullable<int> edificio { get; set; }
        public Nullable<decimal> SalarioHoras { get; set; }
        public Nullable<int> fkUnidadesAcademicas { get; set; }
    
        public virtual CatCuerpoAcademico CatCuerpoAcademico { get; set; }
        public virtual catEdificio catEdificio { get; set; }
        public virtual catProgramaEducativo catProgramaEducativo { get; set; }
        public virtual catTipoContrato catTipoContrato { get; set; }
        public virtual catUnidadesAcademicas catUnidadesAcademicas { get; set; }
        public virtual tblPersonal tblPersonal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblNivelEstudio> tblNivelEstudio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblProduccionAcademica> tblProduccionAcademica { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<catDocumentos> catDocumentos { get; set; }
    }
}
