//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppUscv.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEmergencia
    {
        public int id { get; set; }
        public Nullable<int> fkPersonal { get; set; }
        public Nullable<int> fkParentesco { get; set; }
        public string telefono { get; set; }
        public Nullable<int> fkCiudad { get; set; }
        public Nullable<int> fkEstado { get; set; }
        public string nombreFamiliar { get; set; }
        public Nullable<int> fkLocalidad { get; set; }
    
        public virtual catEstado catEstado { get; set; }
        public virtual catMunicipio catMunicipio { get; set; }
        public virtual catParentesco catParentesco { get; set; }
        public virtual tblPersonal tblPersonal { get; set; }
    }
}
