//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppUscv.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEstudio
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblEstudio()
        {
            this.tblNivelEstudio = new HashSet<tblNivelEstudio>();
            this.tblNivelEstudioAdministrativo = new HashSet<tblNivelEstudioAdministrativo>();
        }
    
        public int id { get; set; }
        public string descripcion { get; set; }
        public Nullable<int> fkCatTipoEstudio { get; set; }
    
        public virtual catTipoEstudio catTipoEstudio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblNivelEstudio> tblNivelEstudio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblNivelEstudioAdministrativo> tblNivelEstudioAdministrativo { get; set; }
    }
}
