//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppUscv.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLibros
    {
        public int id { get; set; }
        public string tituloCapitulo { get; set; }
        public string AutorCapitulo { get; set; }
        public string paginaInicial { get; set; }
        public string paginaFinal { get; set; }
        public Nullable<int> fkProduccionAcademica { get; set; }
    
        public virtual tblProduccionAcademica tblProduccionAcademica { get; set; }
    }
}
