//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppUscv.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProyectosInvestigacionPromep
    {
        public int id { get; set; }
        public string NombreProyecto { get; set; }
        public Nullable<int> fktblPersonalLider { get; set; }
        public Nullable<int> fkDiciplina { get; set; }
        public Nullable<System.DateTime> FechaInicio { get; set; }
        public Nullable<System.DateTime> FechaTermino { get; set; }
    
        public virtual catDisciplinas catDisciplinas { get; set; }
        public virtual tblPersonal tblPersonal { get; set; }
    }
}
