//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppUscv.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblParticipacionDocente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblParticipacionDocente()
        {
            this.catDocumentos = new HashSet<catDocumentos>();
        }
    
        public int ID_Participacion { get; set; }
        public string Evento { get; set; }
        public string Participacion { get; set; }
        public string NombreInstitucion { get; set; }
        public string tipoEvento { get; set; }
        public string Lugar { get; set; }
        public Nullable<int> fkPersonal { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string tipoParticipacion { get; set; }
        public string ponencia { get; set; }
        public string nombrePonencia { get; set; }
    
        public virtual tblPersonal tblPersonal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<catDocumentos> catDocumentos { get; set; }
    }
}
