//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppUscv.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPersonas
    {
        public int id { get; set; }
        public string NombreCompleto { get; set; }
        public byte[] image { get; set; }
        public string curp { get; set; }
        public Nullable<int> numero { get; set; }
        public string ApellidoPaterno { get; set; }
        public string ApellidoMaterno { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> Clave { get; set; }
        public string Usuario { get; set; }
        public Nullable<bool> Status { get; set; }
        public string correo { get; set; }
    }
}
