//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppUscv.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProduccionAcademica
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblProduccionAcademica()
        {
            this.tblLibros = new HashSet<tblLibros>();
            this.tblDatosLaboralesDocente = new HashSet<tblDatosLaboralesDocente>();
            this.catDocumentos = new HashSet<catDocumentos>();
        }
    
        public int id { get; set; }
        public string tituloProducto { get; set; }
        public Nullable<System.DateTime> fechaPublicacion { get; set; }
        public string estadoActual { get; set; }
        public string ConsideraCurriculum { get; set; }
        public Nullable<int> fkidProduccion { get; set; }
        public Nullable<int> fkidFunciones { get; set; }
        public Nullable<int> fkidPais { get; set; }
        public string generado { get; set; }
        public Nullable<int> fkPeriodo { get; set; }
        public string otraProduccion { get; set; }
        public string autor { get; set; }
        public string NomRevista { get; set; }
        public string Paginainicial { get; set; }
        public string paginaFinal { get; set; }
        public string editorial { get; set; }
        public string volumen { get; set; }
        public string issn { get; set; }
        public string proposito { get; set; }
        public string descripcion { get; set; }
        public string DireccionElectronica { get; set; }
        public string IndiceRegistroRevista { get; set; }
        public string NombreEstudioProyectorealizado { get; set; }
        public string alcance { get; set; }
        public string dependenciaBenefisiaria { get; set; }
        public string OtrosParticipantes { get; set; }
        public Nullable<int> Edicion { get; set; }
        public string Tiraje { get; set; }
        public string isbn { get; set; }
        public Nullable<System.DateTime> fechaInicioProyecto { get; set; }
        public string beneficioEconomico { get; set; }
        public Nullable<System.DateTime> fechaElaboracionInforme { get; set; }
        public Nullable<int> NoPaginas { get; set; }
        public string tipoParticipacion { get; set; }
        public string congresoPrecentado { get; set; }
        public Nullable<int> fkmunicipio { get; set; }
        public string productividad { get; set; }
        public string ClasificacionPatente { get; set; }
        public string uso { get; set; }
        public string NumRegistroPatente { get; set; }
        public string usuario { get; set; }
        public Nullable<System.DateTime> fechaRegistroPatente { get; set; }
        public Nullable<int> fkProduccionArtistica { get; set; }
        public string impactoProduccionArtistica { get; set; }
        public string impactoMetodologia { get; set; }
        public string impactoDiseño { get; set; }
        public string impactoinovacion { get; set; }
        public string lugaresPresentados { get; set; }
        public string tipoPrototipo { get; set; }
        public Nullable<int> fkProgramaeducativo { get; set; }
        public Nullable<int> fkinstitucionsuperior { get; set; }
    
        public virtual CatFunciones CatFunciones { get; set; }
        public virtual catInstitucionSuperior catInstitucionSuperior { get; set; }
        public virtual catMunicipio catMunicipio { get; set; }
        public virtual catPais catPais { get; set; }
        public virtual catPeriodo catPeriodo { get; set; }
        public virtual CatProduccion CatProduccion { get; set; }
        public virtual catProduccionArtistica catProduccionArtistica { get; set; }
        public virtual catProgramaEducativo catProgramaEducativo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblLibros> tblLibros { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblDatosLaboralesDocente> tblDatosLaboralesDocente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<catDocumentos> catDocumentos { get; set; }
    }
}
