//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppUscv.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProyecto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblProyecto()
        {
            this.detalletblProyecto_catDocumentos = new HashSet<detalletblProyecto_catDocumentos>();
            this.tblPersonal1 = new HashSet<tblPersonal>();
        }
    
        public int id { get; set; }
        public string tituloProyecto { get; set; }
        public string Patrocinador { get; set; }
        public Nullable<System.DateTime> FechaInicio { get; set; }
        public Nullable<System.DateTime> fechaFin { get; set; }
        public string TipoPatrocinador { get; set; }
        public string AlumnosParticipantes { get; set; }
        public string ActividadesRealizadas { get; set; }
        public string ConsiderarCurriculum { get; set; }
        public Nullable<int> fkPersona { get; set; }
        public string Combocatoria { get; set; }
        public string ProyectoTecnologico { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detalletblProyecto_catDocumentos> detalletblProyecto_catDocumentos { get; set; }
        public virtual tblPersonal tblPersonal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPersonal> tblPersonal1 { get; set; }
    }
}
