//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppUscv.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPortafolioPersonal
    {
        public int id { get; set; }
        public string nombre { get; set; }
        public byte[] documento { get; set; }
        public string tipo { get; set; }
        public string portalURL { get; set; }
        public Nullable<System.DateTime> fechaPublicacion { get; set; }
        public System.DateTime fechaSubida { get; set; }
        public Nullable<System.TimeSpan> horaSubida { get; set; }
        public int fkCatPeriodo { get; set; }
        public int fkTblPersonal { get; set; }
        public string autor { get; set; }
        public Nullable<int> anioPeriodo { get; set; }
    
        public virtual catPeriodo catPeriodo { get; set; }
        public virtual tblPersonal tblPersonal { get; set; }
    }
}
