//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppUscv.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPersonal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblPersonal()
        {
            this.catComprobanteDomicilio = new HashSet<catComprobanteDomicilio>();
            this.catFamiliar = new HashSet<catFamiliar>();
            this.tblCursos = new HashSet<tblCursos>();
            this.tblDatosLaboralesAdministrativos = new HashSet<tblDatosLaboralesAdministrativos>();
            this.tblDatosLaboralesDocente = new HashSet<tblDatosLaboralesDocente>();
            this.tblDesempeñoLaboralAdministrativoDentro = new HashSet<tblDesempeñoLaboralAdministrativoDentro>();
            this.tblDireccionIndividualizada = new HashSet<tblDireccionIndividualizada>();
            this.tblDistincionesPersonal = new HashSet<tblDistincionesPersonal>();
            this.tblDocumentacionPersonal = new HashSet<tblDocumentacionPersonal>();
            this.tblDocumentacionRHDentroUT = new HashSet<tblDocumentacionRHDentroUT>();
            this.tblDocumentacionRHFueraUT = new HashSet<tblDocumentacionRHFueraUT>();
            this.tblEmergencia = new HashSet<tblEmergencia>();
            this.tblEstadia = new HashSet<tblEstadia>();
            this.tblParticipacionDocente = new HashSet<tblParticipacionDocente>();
            this.tblPersonalAsociaciones = new HashSet<tblPersonalAsociaciones>();
            this.tblPersonalDeporte = new HashSet<tblPersonalDeporte>();
            this.tblPortafolioPersonal = new HashSet<tblPortafolioPersonal>();
            this.tblPremiosDocente = new HashSet<tblPremiosDocente>();
            this.tblProyecto = new HashSet<tblProyecto>();
            this.tblProyectosInvestigacionPromep = new HashSet<tblProyectosInvestigacionPromep>();
            this.tblSuperacionProfecional = new HashSet<tblSuperacionProfecional>();
            this.tblTutorias = new HashSet<tblTutorias>();
            this.tblProyecto1 = new HashSet<tblProyecto>();
            this.catCompetencias = new HashSet<catCompetencias>();
            this.catCompetenciaTI = new HashSet<catCompetenciaTI>();
            this.catEnfermedad = new HashSet<catEnfermedad>();
        }
    
        public int id { get; set; }
        public string apellidoPaterno { get; set; }
        public string apellidoMaterno { get; set; }
        public string nombre { get; set; }
        public string RFC { get; set; }
        public string homoclave { get; set; }
        public string curp { get; set; }
        public byte[] curpimagen { get; set; }
        public Nullable<System.DateTime> fechaNacimiento { get; set; }
        public string calleYNumero { get; set; }
        public string sexo { get; set; }
        public Nullable<int> fkLocalidad { get; set; }
        public Nullable<int> fkEstadoCivil { get; set; }
        public byte[] foto { get; set; }
        public Nullable<int> dependientesEconomicos { get; set; }
        public byte[] solicitudEmpleo { get; set; }
        public byte[] comprobanteDomicilio { get; set; }
        public Nullable<int> fkTipoSangre { get; set; }
        public string pasatiempo { get; set; }
        public string tipoRegimenPension { get; set; }
        public string emailPersonal2 { get; set; }
        public string emailPersonal1 { get; set; }
        public string telefonoCel { get; set; }
        public string telefonoCasa { get; set; }
        public string facebook { get; set; }
        public string twitter { get; set; }
        public Nullable<int> horasLaborales { get; set; }
        public byte[] horarioActual { get; set; }
        public string nombreUsuario { get; set; }
        public string contrasenia { get; set; }
        public string status { get; set; }
        public string privilegio { get; set; }
        public byte[] rfcimagen { get; set; }
        public string objetivosGral { get; set; }
        public string telefonoRecados { get; set; }
        public Nullable<int> noInterno { get; set; }
        public Nullable<int> noExterno { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<catComprobanteDomicilio> catComprobanteDomicilio { get; set; }
        public virtual catEdoCivil catEdoCivil { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<catFamiliar> catFamiliar { get; set; }
        public virtual catLocalidad catLocalidad { get; set; }
        public virtual catTipoSangre catTipoSangre { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCursos> tblCursos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblDatosLaboralesAdministrativos> tblDatosLaboralesAdministrativos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblDatosLaboralesDocente> tblDatosLaboralesDocente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblDesempeñoLaboralAdministrativoDentro> tblDesempeñoLaboralAdministrativoDentro { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblDireccionIndividualizada> tblDireccionIndividualizada { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblDistincionesPersonal> tblDistincionesPersonal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblDocumentacionPersonal> tblDocumentacionPersonal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblDocumentacionRHDentroUT> tblDocumentacionRHDentroUT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblDocumentacionRHFueraUT> tblDocumentacionRHFueraUT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblEmergencia> tblEmergencia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblEstadia> tblEstadia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblParticipacionDocente> tblParticipacionDocente { get; set; }
        public virtual tblDocumentosRH tblDocumentosRH { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPersonalAsociaciones> tblPersonalAsociaciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPersonalDeporte> tblPersonalDeporte { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPortafolioPersonal> tblPortafolioPersonal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPremiosDocente> tblPremiosDocente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblProyecto> tblProyecto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblProyectosInvestigacionPromep> tblProyectosInvestigacionPromep { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSuperacionProfecional> tblSuperacionProfecional { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTutorias> tblTutorias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblProyecto> tblProyecto1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<catCompetencias> catCompetencias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<catCompetenciaTI> catCompetenciaTI { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<catEnfermedad> catEnfermedad { get; set; }
    }
}
