//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppUscv.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSuperacionProfecional
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblSuperacionProfecional()
        {
            this.catDocumentos = new HashSet<catDocumentos>();
        }
    
        public int ID_Superacion { get; set; }
        public string NombreCurso { get; set; }
        public Nullable<int> Pais { get; set; }
        public Nullable<System.DateTime> FechaInicio { get; set; }
        public Nullable<System.DateTime> FechaFin { get; set; }
        public string nombreInstitucion { get; set; }
        public Nullable<int> fkPersonal { get; set; }
        public Nullable<int> TotalHoras { get; set; }
        public string tipocurso { get; set; }
        public string tipoCapasitacion { get; set; }
        public string CertificacionAcademica { get; set; }
        public Nullable<System.DateTime> fechaCertificacion { get; set; }
        public string TipoRegion { get; set; }
        public string codigoCertificacion { get; set; }
        public Nullable<System.DateTime> vigenciaCertificacon { get; set; }
        public Nullable<int> fkEstado { get; set; }
        public string ambito { get; set; }
    
        public virtual catEstado catEstado { get; set; }
        public virtual catPais catPais { get; set; }
        public virtual tblPersonal tblPersonal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<catDocumentos> catDocumentos { get; set; }
    }
}
